Portal/urls.py
from django.contrib import admin
from django.urls import path
from resume.views import RecruitmentIndex, profile_forms
urlpatterns = [
    path('',profile_forms),
    path('admin/', admin.site.urls),

]

resume/models.py
from django.db import models


class profile(models.Model):     
      def profilepic(self):
            work_link = models.CharField()
      def skills(self):
            skills = models.CharField()
      def social(self):
            website = models.URLField()
            github = models.URLField()
            twitter = models.URLField()
            instagram = models.URLField()
            facebook = models.URLField()
      user_id = models.CharField(max_length= 120)
      user_name = models.CharField(max_length=100)
      user_age = models.CharField(max_length=100)
      user_eamil = models.EmailField()
      user_phone = models.IntegerField()
      user_profession = models.TextField()  
  
# Table
class Recruitment(models.Model):
  # company name
  company_name = models.CharField(max_length=150)

  # position
  position_name = models.CharField(max_length=100)

  # description
  description = models.TextField(max_length=100)

  # requirement
  requirement = models.TextField()

  # column what to show
  def __str__(self):
    return self.position_name

GENDER_CHOICE = (
    ('M', 'Male'),
    ('F', 'Female'),
)
class Candidate(models.Model):
  pic = models.ImageField(upload_to='profilepic/', null=True, blank=True)
  # name
  first_name = models.CharField(max_length=50)
  middle_name = models.CharField(max_length=50, null=True, blank=True)
  last_name  = models.CharField(max_length=50, null=True, blank=True)

  # personal detail
  recruitment = models.ForeignKey(Recruitment, on_delete=models.CASCADE)
  dob = models.DateField("Date of Birth")
  primary_phone = models.CharField(max_length=12)
  secondary_phone = models.CharField(max_length=12, null=True, blank=True)
  address = models.TextField()
  email = models.EmailField(null=True, blank=True)
  linkedin = models.URLField(null=True, blank=True)
  github = models.URLField(null=True, blank=True)
  gender = models.CharField(max_length=1, choices=GENDER_CHOICE)

  # education
  bachelor_from = models.CharField(max_length=250,null=True, blank=True)
  masters_from = models.CharField(max_length=250, null=True, blank=True)
  certificates = models.TextField(null=True, blank=True)
  description = models.TextField(null=True, blank=True)


  # resume
  resume = models.FileField(upload_to='resume/')

  def image_tag(self):
    from django.utils.html import mark_safe
    return mark_safe('<img src="%s" width="100px" height="100px" />'%(self.pic.url))
    image_tag.short_description = 'Image'

  def fullname(self):
    return f"{self.first_name} {self.middle_name} {self.last_name} "

resume/forms.py
from django.forms import ModelForm
from django import forms
from .models import Candidate

class input_profile(forms.Form):
  # username
  user_image = forms.ImageField()
  user_name = forms.CharField(max_length=100)
  user_mid_name = forms.CharField(max_length=100)
  user_lst_name = forms.CharField(max_length=100)
  # user id
  user_id = forms.CharField(max_length=120)
  # password
  user_pass = forms.CharField(widget=forms.PasswordInput())
  user_con_pass = forms.CharField(widget=forms.PasswordInput())
  # persional detail
  user_age = forms.CharField(max_length=100)
  user_address = forms.Textarea()
  user_eamil = forms.EmailField()
  user_phone = forms.IntegerField()
  user_education = forms.Textarea()
  # skills
  user_profession = forms.Textarea()
  user_skills = forms.CharField()
  # social site
  website = forms.URLField()
  github = forms.URLField()
  twitter = forms.URLField()
  instagram = forms.URLField()
  facebook = forms.URLField()
      
class CandidateProfile(ModelForm):
#  name = user_name
  class Meta:
    model = Candidate
    exclude = []

resume/views.py
from django.shortcuts import render, HttpResponse
from .forms import CandidateProfile, input_profile
from django.views import View

def profile_forms(request):
  if request.method == "POST":
    form = input_profile(request.POST)
    if form.is_valid():
      image = form.cleaned_data['user_image']
      name = form.cleaned_data['user_name']
      mid_name = form.cleaned_data['user_mid_name']
      lst_name = form.cleaned_data['user_lst_name']
      id = form.cleaned_data['user_id']
      password = form.cleaned_data['user_pass']
      con_passwword = form.cleaned_data['user_con_pass']
      age = form.cleaned_data['user_age']
      address = form.cleaned_data['user_address']
      eamil = form.cleaned_data['user_eamil']
      phone = form.cleaned_data['user_phone']
      education = form.cleaned_data['user_image']
      profession = form.cleaned_data['user_profession']
      skills = form.cleaned_data['user_skills']
      website = form.cleaned_data['website']
      github = form.cleaned_data['github']
      twitter = form.cleaned_data['twitter']
      instagram = form.cleaned_data['instagram']
      facebook  = form.cleaned_data['facebook']
      form.save()
    else:
      form = input_profile()
  return render(request, "home.html", {'form': form})

# Create your views here.
class RecruitmentIndex(View):

  # GET
  def get(self, request):
    return render(request, 'index.html', {"form": CandidateProfile })

  # post
  def post(self, request):

    # generate object from input
    p = CandidateProfile(request.POST)

    # validate
    if p.is_valid():
      # save it
      p.save()
    return self.get(request)

resume/templates/home.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <style>
      body {
    background: rgb(99, 39, 120)
}

.form-control:focus {
    box-shadow: none;
    border-color: #BA68C8
}

.profile-button {
    background: rgb(99, 39, 120);
    box-shadow: none;
    border: none
}

.profile-button:hover {
    background: #682773
}

.profile-button:focus {
    background: #682773;
    box-shadow: none
}

.profile-button:active {
    background: #682773;
    box-shadow: none
}

.back:hover {
    color: #682773;
    cursor: pointer
}

.labels {
    font-size: 11px
}

.add-experience:hover {
    background: #BA68C8;
    color: #fff;
    cursor: pointer;
    border: solid 1px #BA68C8
}
  </style>
  <body>
<form method="POST"> 
    {% csrf_token %}
    <div class="container rounded bg-white mt-5 mb-5">
        <div class="row">
            <div class="col-4">
                <div class="align-items-center text-center">{{ form.user_image }}</div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">
                            Username
                        </label>
                        <input type="text" name="user_id" maxlength="120" required id="id_user_id">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            Password
                        </label>
                        <input type="password" name="user_pass" required id="id_user_pass">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            Confirm Password
                        </label>
                        <input type="password" name="user_con_pass" required id="id_user_con_pass">
                    </div>
                </div>
            </div>
            <div class="col-4">
                <div class="p-3 py-5">
                    <div class=" justify-content-between align-items-center mb-3">
                        <h4 class="text-right">Profile Settings</h4>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-4">
                            <label class="labels">
                                Name
                            </label>
                            <input type="text" name="user_name" maxlength="100" required id="id_user_name">
                        </div>
                        <div class="col-md-4">
                            <label class="labels">
                                Middle Name
                            </label>
                            <input type="text" name="user_mid_name" maxlength="100" required id="id_user_mid_name">
                        </div>
                        <div class="col-md-4">
                            <label class="labels">
                                Last name
                            </label
                            input type="text" name="user_lst_name" maxlength="100" required id="id_user_lst_name">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-12">
                            <label class="labels">age</label><input type="number" name="user_age" maxlength="100" required id="id_user_age">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">
                                PhoneNumber
                            </label>
                            <input type="number" name="user_phone" required id="id_user_phone">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">
                                Address
                            </label>
                            <input type="text" name="user_address" required id="id_user_address">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">
                                Email ID
                            </label>
                            <input type="test" name="user_email" required id="id_user_email">
                        </div>
                        <div class="col-md-12">
                            <label class="labels">
                                Education
                            </label>
                            <input type="text" name="user_education" required id="id_user_education">
                        </div>
                    </div>
                    <div class="row mt-3">
                        <div class="col-md-6">
                            <label class="labels">
                                Country
                            </label>
                        </div>
                        <div class="col-md-6">
                            <label class="labels">
                                State/Region
                            </label>
                        </div>
                    </div>
                    <div class="mt-5 text-center"><button class="btn btn-primary profile-button" type="submit" value="Submit">Save Profile</button></div>
                </div>
            </div>
            <div class="col-4">
                <div class="p-3 py-5">
                    <div class=" justify-content-between align-items-center experience">
                        <span>Edit Experience</span>
                        <span class="border px-3 p-1 add-experience"
                        ><i class="fa fa-plus"></i>
                    </div><br>
                    <div class="col-md-12">
                        <label class="labels">
                            Profession
                        </label>
                        <input type="text" name="user_profession" required id="id_user_profission"></div> <br>
                    <div class="col-md-12">
                        <label class="labels">
                            Skill
                        </label>
                        <input type="text" name="user_skills" required id="id_user_skills">
                    </div> <br>
                </div>
                <div class="row mt-3">
                    <div class="col-md-12">
                        <label class="labels">
                            Website
                        </label>
                        <input type="url" name="website" required id="id_website">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            GitHub
                        </label>
                        <input type="url" name="github" required id="id_github">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            twitter
                        </label>
                        <input type="url" name="twitter" required id="id_twitter">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            Instagram
                        </label>
                        <input type="url" name="instagram" required id="id_instagram">
                    </div>
                    <div class="col-md-12">
                        <label class="labels">
                            Facebook
                        </label>
                        <input type="url" name="facebook" required id="id_facebook">
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
    </div>
</form>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

resume/templates/index.html
<form action="." method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>